XS:
  name: size/XS
  lines: 0
  color: FF2D00
S:
  name: size/S
  lines: 10
  color: FF2D00
M:
  name: size/M
  lines: 30
  color: FF2D00
L:
  name: size/L
  lines: 100
  color: FF2D00
XL:
  name: size/XL
  lines: 500
  color: FF2D00
XXL:
  name: size/XXL
  lines: 1000
  color: FF2D00
